spring.application.name=final-todo
springdoc.swagger-ui.path=swagger-ui

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/final_todo
spring.datasource.username=postgres
spring.datasource.password=${DB_PG_PWD:postgres}

external.user.service.baseurl=http://localhost:8083
